### ISSUE TITLE
Push new version to npm

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr-lint#13]
Now that we've got #12 merged, it would be great if we could push a new version to npm.

We may also want to consider:

 - [ ] ~~Updating dependencies~~
 - [ ] Updating the version in `package.json` and `package-lock.json`
 - [ ] Pushing a(nother) new tag to this git repo

/cc @rubenvereecken, who was the last one to push a new version to npm.

**Comment by navarroaxel** [comment]
`Updating dependencies` of this package?
Are we using semver in this project?

The dependencies are really old, IMO that kind of upgrade has the honor of bump a major version. I can take a look to that but not for this easy regex fix.

IMO a dependency shouldn't have a `package-lock.json` because of this:
```
Committing package-lock.json to the source code version control means that the project maintainers and CI systems will use a specific version of dependencies that may or may not match those defined in package.json. Because package-lock.json cannot be added to NPM registry (by design; see NPM shrinkwrap), projects that depend on a project that uses package-lock.json will themselves use package.json to resolve project's dependencies, i.e. what works for project maintainers/ CI systems might not work when the project is used as a dependency.

The origin of this misuse is NPM documentation. It should instead explain that package-lock.json should only be committed to the source code version control when the project is not a dependency of other projects, i.e. package-lock.json should only by committed to source code version control for top-level projects (programs consumed by the end user, not other programs).
```

We should add a `.npmrc` file with:
```
package-lock=false
```

**Comment by owenvoke** [comment]
Been thinking about this, I was going to add GitHub Actions for testing this repo. Do you think it's also worth adding publishing when tags are pushed? 🤔 https://github.com/actions/setup-node

**Comment by rubenvereecken** [comment]
Ooh is that so? I haven't been involved in active development for - at a guess - over three years. I'm sorry, I haven't pushed anything to npm since and don't think I'll be of any use.

**Comment by owenvoke** [comment]
@rubenvereecken, I'm not sure, but I think as you were the last one to release it, you may need to grant another maintainer access. 🤔

Should be listed here: https://www.npmjs.com/package/tldr-lint/access

**Comment by rubenvereecken** [comment]
I didn't realise this was the linter, amazing that that's still going. 

Alright then, I'm happy to give someone else access. @owenvoke since I see you're a tldr organization member I'm adding you.

**Comment by owenvoke** [comment]
I'm happy to add @sbrl and anyone else necessary after. 👍🏻 Cheers @rubenvereecken.

**Comment by owenvoke** [comment]
@sbrl, do you want me to add you as a maintainer for the npm package so you can push the new version? 🤔

**Comment by sbrl** [comment]
Can do, @owenvoke! The more org owners we have there the better I think.

Sorry, it's University induction this week and last week, so I've been a bit busy lol. Should be getting back to normal next week.

**Comment by owenvoke** [comment]
Added you @sbrl, and @agnivade as maintainers. 👍🏻

**Comment by owenvoke** [comment]
Closing this as we've pushed a new version a few months ago, and will be pushing a new version again soon. 👍🏻
