### ISSUE TITLE
Add test for warning for description line that ends with colon or comma

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr-lint#135]
We've never formally tested that this warning is issued, and was only informally tested by the CI issuing it on a separate test case. #131 removes the informal testing, and we should add a proper formal test to ensure behavior / prevent regressions.

Test structure would probably be that within jest, we do `jest.spyOn(console, 'warn')` and then within the test do `expect(console.error).toHaveBeenCalledTimes(1)` and also testing what was passed into the spyed on console.warn (I don't know how to off-hand).

**Comment by waldyrious** [comment]
Same comment as [here](https://github.com/tldr-pages/tldr-lint/issues/56#issuecomment-1537513530).
