### ISSUE TITLE
url validation as part of the automated process

### ISSUE THREAD

**Issue by jtmlis** [tldr-pages/tldr-lint#15]
I had made a typo, and luckily it was found, but I figure this could be done by the automated validation check.

![image](https://user-images.githubusercontent.com/66714119/92593726-926b0400-f26f-11ea-956e-8b60f05eee87.png)

> More information: <hhttps://flameshot.js.org/>.
> More information: <https://flameshot.js.org>.

@sbrl tagging you since you were part of the approval process for that PR.

**Comment by owenvoke** [comment]
This will be included in the next release of the linter, now that https://github.com/tldr-pages/tldr-lint/pull/20 has been merged. 👍🏻

I'm just looking at trying to add checks for multiple URLs (currently it causes a parser error) to maybe enforce a single link if possible.

**Comment by owenvoke** [comment]
Closed as part of v0.0.9
