### ISSUE TITLE
Warn when several adjecent placeholders with different suffix numbers are used

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr-lint#197]
Example:

```
command {{path/to/directory1}} {{path/to/directory2}}
```

Suggest join these placeholders (but don't affect error status because some commands may require just N arguments explicitly):

```
command {{path/to/directory1 path/to/directory2 ...}}
```

**Comment by waldyrious** [comment]
Same comment as [here](https://github.com/tldr-pages/tldr-lint/issues/56#issuecomment-1537513530).
