### ISSUE TITLE
New linter error if the link in more information isn’t reachable anymore

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-lint#280]
To keep the pages up-to-date, we could introduce an linter error if the link in “More information” isn’t working/reachable.

**Comment by kbdharun** [comment]
Can you explain a bit about how we could implement it in Linter?

Would you ping the page's links to check if it is reachable? Or is there something we can use natively?

**Comment by owenvoke** [comment]
I think that this shouldn't really be part of the linter. 🤔 Especially as the linter runs every time a new page is added, we might be DDoSing a lot of sites. 😬

**Comment by kbdharun** [comment]
> I think that this shouldn't really be part of the linter. 🤔 Especially as the linter runs every time a new page is added (or a PR is merged), we might be spamming a lot of sites. 😬

This is exactly what I thought too as we document lesser-known tools too, we might be stressing their servers by sending multiple requests at a time.

**Comment by gutjuri** [comment]
This issue may be closed by https://github.com/tldr-pages/tldr/pull/12506
