### ISSUE TITLE
New linter error if the page in a different language doesn’t exist in English

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-lint#281]
There are some pages in other languages that aren’t available in English. Maybe we need a (warning?) check if the English page exists before adding it to a different language.

To be complete; right now there are:
- 8 pages in linux in different language(s) that aren’t available in English.
- 4 pages in osx in different language(s) that aren’t available in English.
- 1 page in windows in different language(s) that aren’t in English.

**Comment by kbdharun** [comment]
Thanks for the issue.

It is indeed required to create an English page first then a translation (we have this as an informal rule, which we are planning to include in the style guide [checkout https://github.com/tldr-pages/tldr/pull/10755#issuecomment-1743416885]). Implementing a check in the linter would be  best to deal with these pages.

**Comment by owenvoke** [comment]
That would be a great thing to check as part of the linter. 🙌🏻

**Comment by gutjuri** [comment]
https://github.com/tldr-pages/tldr/blob/e7de527dd3dfeb5292b59cc745cfa133538341c8/scripts/check-pr.sh#L49

Looks like the CI does this now, so I suggest closing this issue. I also think that this check fits better into the CI than into the linter.

**Comment by owenvoke** [comment]
Yeah, much nicer as part of CI (definitely think it makes more sense there). 👍🏻 Happy to close this.
