### ISSUE TITLE
New linter error if the filename doesn’t match the command on line 1

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr-lint#282]
I found out at least one page where the filename doesn’t match the command on line 1;
https://github.com/tldr-pages/tldr/blob/main/pages.de/common/aw-backup.md - aws-backup.md

Maybe we can introduce a new linter error to check this.

**Comment by kbdharun** [comment]
This is intentional (we have multiple pages like this), the page title is `aws backup` (the command). And we don't add spaces between files names to prevent breaking clients which may not parse the name as a string.

**Comment by kbdharun** [comment]
> I know but aw-backup seems off. You are right that a `# aws backup` should be named aws-backup.md, but if this doesn’t match, it should trigger right?

We also have pages like `!.md` which uses a different title as the linter doesn't support symbols so the first thing would be to add support for it. Then create a check for same name but to exclude same name with a space in between connecting commands.

**Comment by MasterOdin** [comment]
Related issue: https://github.com/tldr-pages/tldr/issues/5071

From that, there's at least three pages that all have the same command, but different file names, and would have to resolve that case.

**Comment by gutjuri** [comment]
IMO this should be checked by another step in the CI, as in my understanding a Linter only validates syntax, not semantics.
