### ISSUE TITLE
New linter error if the more information URL ends in '/'

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr-lint#290]
Afaik we discourage this. We could also add this to our style-guide.

**Comment by SethFalco** [comment]
For a base domain, like `example.org` vs `example.org/`, it makes no difference, so we can do whatever.

For a domain with a path on it, like `example.org/path/to/dir` vs `example.org/path/to/dir/`, these are entirely different URLs and different web servers may route them differently.

> Assuming no normalization is taking place, /example and /example/ are different paths. 
>
> > From a technical, search engine standpoint, it's certainly permissible for these two URL versions to contain different content.
> >
> > — https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash 
>
> — https://matrix.to/#/%23tldr-pages%3Amatrix.org/%24p4cGxZ9fwKkmMfNux8c6m9I_xPEXZdIYq3IgAG8G8Zs?via=one.ems.host&via=gitter.im&via=matrix.org&via=yatrix.org
