### ISSUE TITLE
New linter error if, in the command example, there is a leading or trailing space

### ISSUE THREAD

**Issue by vitorhcl** [tldr-pages/tldr-lint#293]
To be clear, we could check if there is a space after the opening backtick or a space before the closing backtick. I don't think it has any effect on a command on any platform.

I fixed some of these pages on https://github.com/tldr-pages/tldr/pull/11850.

**Comment by kbdharun** [comment]
cc @sebastiaanspeck, what do you think?

**Comment by gutjuri** [comment]
Spaces after the opening tick are fine to forbid IMO. Spaces at the end of a command could be deliberate. E.g. `echo \ ` can be used in common Linux shells to print a space character.
