### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr-lint#54]
Has anyone thought of adding some nice colors to the output of tldr-lint (at least when stdout/stderr is a terminal)?

It would make using it a lot easier, IMO.

**Comment by bl-ue** [comment]
I wonder if sorting the errors by TLDRXXX number would be good too...but that's just a thought, not really something we should consider at this point.

**Comment by owenvoke** [comment]
I think for the Node client we are using [chalk](https://www.npmjs.com/package/chalk) so we could probably use that here too. To be honest, I find it pretty readable already, but I don't mind either way.
