### ISSUE TITLE
Bot should detect unclosed curly braces

### ISSUE THREAD

**Issue by xeruf** [tldr-pages/tldr-lint#76]
[This commit](https://github.com/tldr-pages/tldr/commit/443d1da898086564ab343eefb10ff46315a7fee1#diff-83dbb0d1c631c1f5de07d28506db0756b728f046436d4ae0524d7f05d46c2364R8) was accepted by the bot even though there was a breaking issue at line 8: A curly parentheses in an example wasn't closed properly.
Such an issue is hard to notice, so it would be nice if your neat build bot could report that as well.

**Comment by owenvoke** [comment]
I guess if there's a set of `{{` without a closing `}}` before another `{{` or EOL. 👍🏻

**Comment by waldyrious** [comment]
Same comment as [here](https://github.com/tldr-pages/tldr-lint/issues/56#issuecomment-1537513530).
