### ISSUE TITLE
Allow `N/A` as link

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr-lint#83]
As discussed in https://github.com/tldr-pages/tldr/issues/5510#issuecomment-811381061, we should use `> More information: N/A` for pages which have no suitable online documentation to explicitly mention that. This would however need a slight adjustment of tldr-lint, since it expects a `<...>` after `More information:`.

**Comment by waldyrious** [comment]
Same comment as [here](https://github.com/tldr-pages/tldr-lint/issues/56#issuecomment-1537513530).
