### ISSUE TITLE
feature request: do not allow links

### ISSUE THREAD

**Issue by frazjp65** [tldr-pages/tldr-lint#9]
Do not allow markdown links as they do not display properly in the command line. This is in response to [a review that I received](https://github.com/tldr-pages/tldr/pull/1725#pullrequestreview-80445378).

**Comment by pxgamer** [comment]
We now support a new format for links in pages ([example](https://raw.githubusercontent.com/tldr-pages/tldr/fa21dc0a079d205d9b3c3b900e7dd60c2c976cb4/pages/common/hg.md)):
```markdown
> Homepage: <https://...>.
```

So it would be good to lint these (and exclude the `[...](https://...)` format of links).

**Comment by owenvoke** [comment]
Closing as this is basically covered by the new rules that will be released soon. 👍🏻
