### ISSUE TITLE
Replace Generic Rules with EditorConfig

### ISSUE THREAD

**Issue by SethFalco** [tldr-pages/tldr-lint#94]
Some rules are defined and implemented here that are generic and can be handled already by EditorConfig.
We have an [`.editorconfig`](https://github.com/tldr-pages/tldr/blob/main/.editorconfig) file defined in [tldr-pages/tldr](https://github.com/tldr-pages/tldr).

I think we can reduce the code surface by using something that enforces EditorConfig instead.
This means less code to maintain, while having access to more rules.

| Error Code | Description | Rule
|---|---|---
| TLDR009 | Page should contain a newline at end of file | `insert_final_newline`
| TLDR010 | Only Unix-style line endings allowed | `end_of_line`
| TLDR012 | Page should contain no tabs | `indent_style`

### Prettier
I think the best way would be to delegate some rules to [Prettier](https://prettier.io/).
It documents that we can read an `.editorconfig` file which can use it to override rules. ([More Info](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options))

This would cover:
* `TLDR010`
* `TLDR012`

Prettier doesn't support the other properties that would help out yet, though:
* `insert_final_newline` for `TLDR009`

### GitHub Actions
This one would be out of scope for this repository, but we could just scrap those rules and use a GitHub Action.

#### setup-editorconfig-checker
[setup-editorconfig-checker](https://github.com/kasperhesthaven/setup-editorconfig-checker) might be good, and it uses [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) which is still maintained.

#### EditorConfig-Action
[EditorConfig-Action](https://github.com/zbeekman/EditorConfig-Action) wins by star count, but this just uses [jedmao/eclint](https://github.com/jedmao/eclint) under the hood, which is an archived and unmaintained project.

### EditorConfig JavaScript Core
Alternatively, we could use [EditorConfig JavaScript Core](https://github.com/editorconfig/editorconfig-core-js) to parse the `.editorconfig` file, and apply the rule from there instead. That would defeat the point, as we'd still have to implement ourselves anyway, though. 🤔

**Comment by marchersimon** [comment]
I'm not sure if breaking up the rules to multiple services would make it easier. I feel like this can get confusing. Also, what about https://github.com/tldr-pages/tldr-lint/? Offline, I don't have the possibilities of GitHub Actions or Prettier.

**Comment by marchersimon** [comment]
(Also, pinging some contributors, since they don't watch this repo: @sbrl @navarroaxel @CleanMachine1)

**Comment by SethFalco** [comment]
Ahh, I didn't consider offline use. 🤔 
The Prettier comment doesn't apply, as this project is in JavaScript, so it can just depend on Prettier.

As for GitHub actions, fair enough, that wouldn't work.

**Comment by owenvoke** [comment]
I'd have to agree with @marchersimon, I think having the offline capability as well as it being part of a centralised tool makes more sense.

Although, I still think that in future it would be nice to possibly rewrite the `tldr-lint` tool to a different lexer, etc.

**Comment by MasterOdin** [comment]
Given that this repo is _very_ stable and doesn't change very often, I think replacing the built-in parse rules with a third party dependency would __raise__ maintainer workload as we'd now have to keep track of yet another dependency and its new versions. The code that would be removed would also be the smallest, simplest rules that it wouldn't really give all that much less code to maintain.

**Comment by SethFalco** [comment]
Fair enough, I'll concede to that.
I'll actually close this issue already. Looking back at my original issue and after hearing feedback, I agree it's not worthwhile.
